### ISSUE TITLE
One image class

### ISSUE THREAD

**Issue by tentenponce** [perseus784/BvS#7]
I've tried this but I have only 1 class of image. When I run the `trainer.py`, the **loss** always giving me 0.  Is this still applicable if I have only 1 class of image?

**Comment by perseus784** [comment]
if it only has one class, then what do you want to classify at all?

**Comment by tentenponce** [comment]
It seems that I misunderstood how Image Classifiers work, it requires to have atleast 2 class to identify which is which. What I actually want is similarity percentage of the image base on the image registered on the model. For my use case, I want to identify a certain ID, I achieve it by training it with two classes. First class is the specific ID that I want to recognize, and the second class were just random IDs.
